# Defines the theme to use. Possible values are:
# - dark
# - light
# The default is light.
theme = "light"

# Defines the application language.
#
# May be any valid IETF BCP 47 language tag. If the indicated language
# is not supported, fallback to a supported one is guaranteed.
#
# Supported languages are:
#  - en-US
#  - fr-FR
# The default is fr-FR.
#
# See also: https://www.rfc-editor.org/info/bcp47
lang = "fr-FR"

# Define the name of the content file.
# The default is contenu.txt
content_file_name = "contenu.txt"

# Defines how the number of evidence in a directory is displayed.
# Possible values are:
# - letters
# - western arabic numerals
# The default is "western arabic numerals"
number_representation = "western arabic numerals"
