[application]

# App (Project) Name
name = "Loutre"

# Dioxus App Default Platform
# web, desktop, fullstack
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# assets file folder
asset_dir = "assets"

[bundle]
identifier = "fr.cnil"
publisher = "Commission nationale de l’informatique et des libertés (CNIL)"
icon = [
	"assets/favicon.png",
	"assets/favicon.ico",
]
category = "Utility"

[bundle.windows]
tsp = true
icon_path = "assets/favicon.ico"
allow_downgrades = true

[bundle.windows.webview_install_mode.OfflineInstaller]
silent = true
